//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaswellSQLConversion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EpitaxySQLEntities : DbContext
    {
        public EpitaxySQLEntities()
            : base("name=EpitaxySQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Layer> Layers { get; set; }
        public virtual DbSet<Layer_Result> Layer_Results { get; set; }
        public virtual DbSet<Pocket> Pockets { get; set; }
        public virtual DbSet<PROMIS_Part> PROMIS_Parts { get; set; }
        public virtual DbSet<QW_Xray> QW_Xrays { get; set; }
        public virtual DbSet<Reactor> Reactors { get; set; }
        public virtual DbSet<Reagent_Avail> Reagent_Avails { get; set; }
        public virtual DbSet<Reagent_State> Reagent_States { get; set; }
        public virtual DbSet<Reagent> Reagents { get; set; }
        public virtual DbSet<Run> Runs { get; set; }
        public virtual DbSet<Wafer_Map> Wafer_Maps { get; set; }
        public virtual DbSet<ReactorEx> ReactorExes { get; set; }
    }
}
