//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaswellSQLConversion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pocket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pocket()
        {
            this.Wafer_Map = new HashSet<Wafer_Map>();
        }
    
        public int Pocket_ID { get; set; }
        public Nullable<int> Run_ID { get; set; }
        public Nullable<int> Pocket_Pos { get; set; }
        public string Wafer_ID { get; set; }
        public string Wafer_Prep { get; set; }
        public string Size { get; set; }
        public Nullable<double> Surfscan_Density { get; set; }
        public Nullable<double> Surfscan_Count { get; set; }
        public string Comments { get; set; }
        public string Res_1 { get; set; }
        public string Status { get; set; }
        public string Release_To { get; set; }
        public Nullable<System.DateTime> Status_Change_Date { get; set; }
        public string Release_Batch { get; set; }
        public Nullable<System.DateTime> PROMIS_Transact_Date { get; set; }
        public Nullable<int> PROMIS_Part_ID { get; set; }
        public string PROMIS_Component { get; set; }
        public string PROMIS_Wafer_ID { get; set; }
        public string PROMIS_Designation { get; set; }
        public Nullable<bool> PROMIS_Transfer { get; set; }
        public string PROMIS_Lot_Name { get; set; }
        public Nullable<int> PROMIS_Scrap_Code_ID { get; set; }
        public string PROMIS_Scrap_Report_ID { get; set; }
        public byte[] upsize_ts { get; set; }
        public string Substrate_Part_ID { get; set; }
        public string Prepped { get; set; }
        public string Loaded { get; set; }
        public string Unloaded { get; set; }
    
        public virtual PROMIS_Part PROMIS_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wafer_Map> Wafer_Map { get; set; }
    }
}
