//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaswellSQLConversion
{
    using System;
    using System.Collections.Generic;
    
    public partial class QW_Xray
    {
        public int QW_Xray_ID { get; set; }
        public Nullable<int> Pocket_ID { get; set; }
        public Nullable<double> QWQB { get; set; }
        public Nullable<double> ZOM { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
