//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaswellSQLConversion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reactor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reactor()
        {
            this.Reagent_Avail = new HashSet<Reagent_Avail>();
            this.Runs = new HashSet<Run>();
        }
    
        public int Reactor_ID { get; set; }
        public string Reactor_Name { get; set; }
        public string TEM_Path { get; set; }
        public string POP_Path { get; set; }
        public string RTPL_Path { get; set; }
        public string Reflectivity_Path { get; set; }
        public string LTPL_Path { get; set; }
        public string x_ray_Path { get; set; }
        public string SIMS_Path { get; set; }
        public string CV_Path { get; set; }
        public string TEM_Images_Path { get; set; }
        public string Datasheet_Path { get; set; }
        public string Databook_Path { get; set; }
        public string Datasheet_Archive_Path { get; set; }
        public string Recipe_Reader_Path { get; set; }
        public string Recipe_Archive_Path { get; set; }
        public Nullable<int> Max_Loading { get; set; }
        public string PROMIS_Location { get; set; }
        public byte[] upsize_ts { get; set; }
        public string SurfScan_Path { get; set; }
        public string Tool_Owner { get; set; }
        public string XPS_Path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reagent_Avail> Reagent_Avail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Run> Runs { get; set; }
    }
}
