//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaswellSQLConversion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reagent_Avail
    {
        public int Reagent_Avail_ID { get; set; }
        public Nullable<int> Reactor_ID { get; set; }
        public Nullable<int> Reagent_ID { get; set; }
        public Nullable<bool> Source_Avail { get; set; }
        public Nullable<bool> Dilution_Avail { get; set; }
        public Nullable<bool> Pusher_Avail { get; set; }
        public Nullable<bool> Inject_Avail { get; set; }
        public Nullable<bool> Pressure_Avail { get; set; }
        public Nullable<bool> EPISON_Avail { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual Reactor Reactor { get; set; }
    }
}
